import Require from "./require.js"

export default [{
        path: '',
        redirect: '/wrap/center',
    }, {
        path: 'center',
        name: '个人中心',
        component: Require.mycenter,
    }, {
        path: 'track',
        name: '我的足迹',
        component: Require.mytrack,
    }, {
        path: 'collect',
        name: '我的收藏',
        component: Require.mycollect,
    }, {
        path: 'accountSetting',
        name: '账户设置',
        component: Require.accountSetting,
    }, {
        path: 'news',
        name: '消息通知',
        component: Require.news,
    }, {
        path: 'mycomment',
        name: '账户设置',
        component: Require.mycomment,
    }, {
        path: 'myshop',
        name: '已购资源',
        component: Require.myshop,
    }, {
        path: 'accountBindOrganization',
        name: '账户设置-绑定机构',
        component: Require.accountBindOrganization,
    }, {
        path: 'accountBindOrganizeOver',
        name: '账户设置-绑定机构',
        component: Require.accountBindOrganizeOver,
    }, {
        path: 'accountBindTel',
        name: '账户设置-绑定手机',
        component: Require.accountBindTel,
    }, {
        path: 'accountVerify',
        name: '账户设置-验证身份',
        component: Require.accountVerify,
    }, {
        path: 'accountSetPwd',
        name: '账户设置-设置密码',
        component: Require.accountSetPwd,
    }, {
        path: 'accountFindPwd',
        name: '账户设置-找回密码',
        component: Require.accountFindPwd,
    }, {
        path: 'accountOver',
        name: '账户设置-完成',
        component: Require.accountOver,
    }, {
        path: 'shippingAddress',
        name: '收货地址',
        component: Require.shippingAddress,
    }, {
        path: 'listOfAddress',
        name: '已设置收货地址',
        component: Require.listOfAddress,
    }, {
        path: 'EditPersonaInfo',
        name: '编辑个人资料',
        component: Require.EditPersonaInfo,
    }, {
        path: 'OrderDetail',
        name: '订单详情',
        component: Require.OrderDetail,
    }, {
        path: 'accountBindEmail',
        name: '账户设置-绑定邮箱',
        component: Require.accountBindEmail,
    }, {
        path: 'successBindTel',
        name: '手机绑定成功',
        component: Require.successBindTel,
    }, {
        path: 'successBindEmail',
        name: '邮箱绑定成功',
        component: Require.successBindEmail,
    }, {
        path: 'successEditTel',
        name: '手机修改成功',
        component: Require.successEditTel,
    }, {
        path: 'successEditEmail',
        name: '邮箱修改成功',
        component: Require.successEditEmail,
    }, {
        path: 'accountVerifyTel',
        name: '账户设置-验证身份-手机验证',
        component: Require.accountVerifyTel,
    },
     {
        path: 'accountVerifyEmail',
        name: '账户设置-验证身份-邮箱验证',
        component: Require.accountVerifyEmail,
    }, {
        path: 'successVerifyTel',
        name: '手机验证成功',
        component: Require.successVerifyTel,
    }, {
        path: 'successVerifyEmail',
        name: '邮箱修改成功',
        component: Require.successVerifyEmail,
    }, {
        path: 'accountNewTel',
        name: '重新绑定电话',
        component: Require.accountNewTel,
    }, {
        path: 'accountNewEmail',
        name: '重新绑定邮箱',
        component: Require.accountNewEmail,
    },{
        path: 'amend',
        name: '重新绑定邮箱验证身份',
        component: Require.amend,
},{
        path: 'myOrder',
        name: '我的订单',
        component: Require.myOrder,
    },{
        path: 'UpdateAddress',
        name: '修改地址',
        component: Require.UpdateAddress,
    },{
        path: 'PaperDetail',
        name: '修改地址',
        component: Require.PaperDetail,
    },
 ]
